### String methods practice

s="this is sample string used for practice"

print("--------------capitalize-------------------")
print(s.capitalize())

print("--------------count(ele)-------------------")
print(s.count("s"))
print("-------------endswith(substring)--------------------")
print(s.endswith("actice"))
print("---------------find(ele)------------------")
print(s.find("q"))
print("-------------index(ele)--------------------")
print(s.index("a"))
print("-------------isalnum()--------------------")
print(s.isalnum())
print("------------isalptha()---------------------")
print(s.isalpha())
print("--------------isdigit()-------------------")
print(s.isdigit())
print("------------isspace()---------------------")
print(s.isspace())
print("---------------islower()------------------")
print(s.islower())
print("--------------isupper()-------------------")
print(s.isupper())
print("------------upper()---------------------")
print(s.upper())
print("------------lower()---------------------")
print(s.lower())
print("-----------replace(what, with)----------------------")
print(s.replace("is","IISS"))
print("---------------join------------------")
print(", ".join(['a','b','c','d','e']))
print("----------------split('char')-----------------")
print(s.split(" "))
print("----------------strip()-----------------")
print(s.strip())
print("-------------strip(char)--------------------")
print(s.strip("t"))
print("-------------swapcase()--------------------")
print(s.swapcase())
print("-------------title()--------------------")
print(s.title())