### String practice

line="This is sample string used"
line.capitalize()
line.count("i")
line.find("i")
line.index("i")
line.isalnum()
line.isdigit()
line.isspace()
line.isalpha()
line.islower()
line.isupper()
line.startswith("it")
line.endswith(".")
line.title()
line.swapcase()
line.upper()
line.lower()
# print(line.replace("ed","52"))
line.strip()
print(line.split())
# print(line)
# print(",".join(line))
